/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProdutosRouteImport } from './routes/_app.produtos'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppClientesRouteImport } from './routes/_app.clientes'
import { Route as AppOrdensIndexRouteImport } from './routes/_app.ordens.index'
import { Route as AppOrdensNovaRouteImport } from './routes/_app.ordens.nova'
import { Route as AppOrdensIdRouteImport } from './routes/_app.ordens.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProdutosRoute = AppProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdensIndexRoute = AppOrdensIndexRouteImport.update({
  id: '/ordens/',
  path: '/ordens/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdensNovaRoute = AppOrdensNovaRouteImport.update({
  id: '/ordens/nova',
  path: '/ordens/nova',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdensIdRoute = AppOrdensIdRouteImport.update({
  id: '/ordens/$id',
  path: '/ordens/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/clientes': typeof AppClientesRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/produtos': typeof AppProdutosRoute
  '/ordens/$id': typeof AppOrdensIdRoute
  '/ordens/nova': typeof AppOrdensNovaRoute
  '/ordens/': typeof AppOrdensIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/clientes': typeof AppClientesRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/produtos': typeof AppProdutosRoute
  '/ordens/$id': typeof AppOrdensIdRoute
  '/ordens/nova': typeof AppOrdensNovaRoute
  '/ordens': typeof AppOrdensIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/clientes': typeof AppClientesRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/produtos': typeof AppProdutosRoute
  '/_app/ordens/$id': typeof AppOrdensIdRoute
  '/_app/ordens/nova': typeof AppOrdensNovaRoute
  '/_app/ordens/': typeof AppOrdensIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/clientes'
    | '/configuracoes'
    | '/produtos'
    | '/ordens/$id'
    | '/ordens/nova'
    | '/ordens/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/clientes'
    | '/configuracoes'
    | '/produtos'
    | '/ordens/$id'
    | '/ordens/nova'
    | '/ordens'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/sitemap.xml'
    | '/_app/clientes'
    | '/_app/configuracoes'
    | '/_app/produtos'
    | '/_app/ordens/$id'
    | '/_app/ordens/nova'
    | '/_app/ordens/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/produtos': {
      id: '/_app/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AppProdutosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ordens/': {
      id: '/_app/ordens/'
      path: '/ordens'
      fullPath: '/ordens/'
      preLoaderRoute: typeof AppOrdensIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ordens/nova': {
      id: '/_app/ordens/nova'
      path: '/ordens/nova'
      fullPath: '/ordens/nova'
      preLoaderRoute: typeof AppOrdensNovaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ordens/$id': {
      id: '/_app/ordens/$id'
      path: '/ordens/$id'
      fullPath: '/ordens/$id'
      preLoaderRoute: typeof AppOrdensIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppClientesRoute: typeof AppClientesRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppProdutosRoute: typeof AppProdutosRoute
  AppOrdensIdRoute: typeof AppOrdensIdRoute
  AppOrdensNovaRoute: typeof AppOrdensNovaRoute
  AppOrdensIndexRoute: typeof AppOrdensIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClientesRoute: AppClientesRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppProdutosRoute: AppProdutosRoute,
  AppOrdensIdRoute: AppOrdensIdRoute,
  AppOrdensNovaRoute: AppOrdensNovaRoute,
  AppOrdensIndexRoute: AppOrdensIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
